### ISSUE TITLE
chirimen-oh/tutorialsに統合するのが好ましいと思います

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/tutorials-TY51822r3#1]

**Comment by satakagi** [comment]
場所はhttps://github.com/chirimen-oh/tutorials/tree/master/TY51822r3
と思います。

**Comment by dynamis** [comment]
tutorial.chirimen.org 自体をボード毎のディレクトリに入れる想定の構造にしていたので

https://github.com/chirimen-oh/tutorials/

配下に各ボードのものを用意し、トップは CHIRIMEN 全体の説明というようにするのが本来の趣旨かな。コミュニティ全体として TY51822r3 上のこの実装を CHIRIMEN を冠した移植・実装の一つとして認める合意をした上で、tutorial.chirimen.org が突然変わると驚く人の減る 3-4 月に統合作業ができると良さそうに思います (多分その想定で取りあえず別途作られた？)

**Comment by dynamis** [comment]
ミーティングにて合意が取れたので tutorial.chirimen.org 配下に移動する作業を進めていきます。
@TakumiNishina よろしくっ

**Comment by dynamis** [comment]
DONE: https://github.com/chirimen-oh/tutorials/tree/master/ty51822r3/ja
